---
- name: 'Start port-forward6 for {{ VIRTUAL_HOST }}'
  docker_container:
    name: 'port_forward6_for_{{ VIRTUAL_HOST | replace(",", "-") }}'
    image: 'gmaniac/port-forward6'
    state: started
    restart_policy: always
    recreate: yes
    #restart: yes
    pull: yes
    published_ports: '{{ FORWARD_PUBLISHED_PORTS | default(omit) }}'
    env:
      REMOTE_HOST: '{{ REMOTE_HOST }}'
      REMOTE_PORT: '{{ REMOTE_PORT }}'
      LOCAL_PORT: '{{ LOCAL_PORT }}'
      VIRTUAL_HOST: '{{ VIRTUAL_HOST }}'
      LETSENCRYPT_HOST: '{{ VIRTUAL_HOST }}'
      LETSENCRYPT_EMAIL: '{{ LETSENCRYPT_EMAIL }}'
