---
## In general, all roles are expecting cent/os as base system.
## Although, with little manual help, ubuntu is possible as
## well. Use the libvirtd-role (bum/roles/libvirtd) to check
## the required packages and adjust accordingly.
## Vagrant is required in a more modern version than distributed
## with e.g. xenial in Ubuntu or cent/os 7.
## For Ubuntu, you can take care of the dependencies by installing
## the vagrant-package (with all dependencies), unsinstall it
## and then install with the commands as used in the libvirtd
## role. Afterwards (e.g. after all base work is done),
## generating a vm is possible, as usual on bum5.
##
## run with `ansible-playbook -i production site.yml -l homeserver`
##
- hosts: homeserver
  user: root
  roles:
#    - libvirtd
    - { role: generic_vm,
        vm_vagrant_template: "centos/7",
        vm_memory: 4096,
        vm_cpus: 4,
        tags: "jens-home-vm",
        vm_name: "jens-home-vm",
        vm_macaddress: "52:54:00:20:00:25",
        vm_ipaddress: "192.168.200.25",
        vm_ipv6_address: "fe80::225:90ff:200::25",
        vm_ipv6_prefix: 80,
        vm_libvirt_network: '{{ libvirtd_networks.jensnet200 }}',
        vm_port_forwardings: [ { source: 5601, dest: 5601, proto: "tcp" },
                               { source: 8180, dest: 80, proto: "tcp" },
                               { source: 8118, dest: 8118, proto: "tcp" } ],
        vm_volumes: [ { name: "jens-home-vm_option-disk1.img", size: "5000", target: vdb } ] }
    - { role: generic_vm,
        vm_vagrant_template: "centos/7",
        vm_memory: 2048,
        vm_cpus: 1,
        tags: "jens-home-http",
        vm_name: "jens-home-http",
        vm_macaddress: "52:54:00:20:00:80",
        vm_ipaddress: "192.168.200.80",
        vm_ipv6_address: "fe80::225:90ff:200::80",
        vm_ipv6_prefix: 80,
        vm_libvirt_network: '{{ libvirtd_networks.jensnet200 }}',
        vm_port_forwardings: [ { source: 801, dest: 80, proto: "tcp" },
                               { source: 4431, dest: 443, proto: "tcp" } ],
        vm_volumes: [ { name: "jens-home-http_option-disk1.img", size: "500", target: vdb } ] }
    - { role: generic_vm,
        vm_vagrant_template: "centos/7",
        vm_memory: 2048,
        vm_cpus: 2,
        tags: "jens-home-build",
        vm_name: "jens-home-build",
        vm_macaddress: "52:54:00:20:00:50",
        vm_ipaddress: "192.168.200.50",
        vm_ipv6_address: "fe80::225:90ff:200::50",
        vm_ipv6_prefix: 80,
        vm_libvirt_network: '{{ libvirtd_networks.jensnet200 }}',
        vm_port_forwardings: [ { source: 802, dest: 80, proto: "tcp" } ],
        vm_volumes: [ { name: "jens-home-build_option-disk1.img", size: "500", target: vdb } ] }
  tags: home_vm_create

## After vm generation and startup - usual roles / plays for the vms
## Maybe migrated to own files later on

- hosts: homeserver_vm
  user: root
  roles:
    - { role: authorized_keys, tags: "authorized_keys" }
    - { role: option-disk, tags: "option-disk" }
    - { role: convenience, tags: "convenience" }
    - { role: convenience-mail, tags: "convenience-mail" }
    - { role: convenience-yum, tags: "convenience-yum" }
    - { role: fail2ban, tags: "fail2ban" }
    - { role: privoxy, tags: "privoxy" }
    - { role: zoneminder, vars: { VIRTUAL_HOST: "zm.home.gecius.de" }, tags: "zoneminder"}
    - { role: remote-logging, vars: { LOGHOST: "192.168.178.25", LOCAL_SYSLOG: "no" }, tags: "remote-logging" }
  tags: home_vm_init

- hosts: homeserver_http
  user: root
  roles:
    - { role: authorized_keys, tags: "authorized_keys" }
    - { role: option-disk, tags: "option-disk" }
    - { role: convenience, tags: "convenience" }
    - { role: convenience-mail, tags: "convenience-mail" }
    - { role: convenience-yum, tags: "convenience-yum" }
    - { role: letsencrypt-nginx-proxy, tags: "http-proxy" }
    - { role: fail2ban, tags: "fail2ban" }
    - { role: remote-logging, vars: { LOGHOST: "192.168.178.25", LOCAL_SYSLOG: "no" }, tags: "remote-logging" }
  tags: home_vm_init

- hosts: homeserver_build
  user: root
  roles:
    - { role: authorized_keys, tags: "authorized_keys" }
    - { role: option-disk, tags: "option-disk" }
    - { role: convenience, tags: "convenience" }
    - { role: convenience-mail, tags: "convenience-mail" }
    - { role: convenience-yum, tags: "convenience-yum" }
    - { role: convenience-build, tags: "convenience-build" }
    - { role: fail2ban, tags: "fail2ban" }
    - { role: remote-logging, vars: { LOGHOST: "192.168.178.25", LOCAL_SYSLOG: "no" }, tags: "remote-logging" }
  tags: home_vm_init

#- hosts: homeserver
#  user: root
#  roles:
#    - { role: sync-phone-img, tags: "sync-phone-img" }