---
- hosts: other
  remote_user: root
  roles:
    - { role: authorized_keys, tags: "authorized_keys" }
    - { role: option-disk, tags: "option-disk" }
    - { role: convenience, tags: "convenience" }
    - { role: convenience-mail, tags: "convenience-mail" }
    - { role: convenience-yum, tags: "convenience-yum" }
    - { role: znc, tags: "znc" }
    - { role: remote-logging, vars: { LOCAL_SYSLOG: '' }, tags: "remote-logging" }
    - { role: privoxy, tags: "privoxy" }
#    - { role: gps-server, tags: "gps-server" }
    - { role: container_mqtt, tags: "mqtt" }
    - { role: mqtt_exporter_container, tags: "mqtt-exporter"}

- hosts: http
  remote_user: root
  vars:
    VIRTUAL_HOST: other.gecius.de
  roles:
    - nginx
  tags:
    other.gecius.de

# Sync SSL-certs + dh-param for znc on other.gecius.de
- hosts: other
  remote_user: root
  vars:
    sync_source_host_ansible: jens-http
    sync_source_host: 192.168.175.80
    sync_source: /srv/nginx/certs/other.gecius.de
    sync_target_dir: /srv/znc/conf/certs
  roles:
    - { role: rompe.sync_dir_from_other_host, tags: "sync_dir" }
  tags:
    certsync

- hosts: other
  remote_user: root
  vars:
    sync_source_host_ansible: jens-http
    sync_source_host: 192.168.175.80
    sync_source: /srv/nginx/certs/dhparam.pem
    sync_target_dir: /srv/znc/conf/certs
  roles:
    - { role: rompe.sync_dir_from_other_host, tags: "sync_dir" }
  tags:
    certsync-dh

- hosts: other
  user: root
  vars:
    VIRTUAL_HOST: nodex-jens-other.gecius.de
  roles:
    - node_exporter_container
  tags:
    - node_exporter

- hosts: other
  user: root
  vars:
    TBD: test
  roles:
    - coturn
  tags:
    coturn

- hosts: other
  user: root
  roles:
    - tel_check
  tags:
    - tel_check

- hosts: other
  user: root
  vars:
    VIRTUAL_HOST: "other-http.gecius.de"
    REMOTE_HOST: "192.168.175.80"
    REMOTE_PORT: "80"
    LOCAL_PORT: "80"
    FORWARD_PUBLISHED_PORTS: "80:80"
  roles:
    - firewall
    - port-forward6
  tags:
    - other_http

- hosts: other
  user: root
  vars:
    VIRTUAL_HOST: "other-https.gecius.de"
    REMOTE_HOST: "192.168.175.80"
    REMOTE_PORT: "443"
    LOCAL_PORT: "443"
    FORWARD_PUBLISHED_PORTS: "443:443"
  roles:
    - firewall
    - port-forward6
  tags:
    - other_http
