---
- name: 'Start port-forward for {{ VIRTUAL_HOST }}'
  docker_container:
    name: 'port_forward_for_{{ VIRTUAL_HOST | replace(",", "-") }}'
    image: 'marcnuri/port-forward'
    state: started
    restart_policy: always
    recreate: yes
    #restart: yes
    pull: yes
    published_ports: '{{ FORWARD_PUBLISHED_PORTS | default(omit) }}'
    env:
      REMOTE_HOST: '{{ REMOTE_HOST }}'
      REMOTE_PORT: '{{ REMOTE_PORT }}'
      VIRTUAL_HOST: '{{ VIRTUAL_HOST }}'
      LETSENCRYPT_HOST: '{{ VIRTUAL_HOST }}'
      LETSENCRYPT_EMAIL: '{{ LETSENCRYPT_EMAIL }}'
